# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/PlanRequests.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18proto/PlanRequests.proto\"s\n\x0f\x45\x64itPlanRequest\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12\x17\n\x0fnumberOfMinutes\x18\x02 \x01(\t\x12\x18\n\x10musicSuggestions\x18\x03 \x01(\t\x12\x18\n\x10musicCollections\x18\x04 \x01(\t\"\xaa\x01\n\x11\x43reatePlanRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x17\n\x0fnumberOfMinutes\x18\x03 \x01(\x05\x12\x18\n\x10musicSuggestions\x18\x04 \x01(\t\x12\x18\n\x10musicCollections\x18\x05 \x01(\x05\x12\x12\n\nmonthlyFee\x18\x06 \x01(\x02\x12\x11\n\tannualFee\x18\x07 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.PlanRequests_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EDITPLANREQUEST']._serialized_start=28
  _globals['_EDITPLANREQUEST']._serialized_end=143
  _globals['_CREATEPLANREQUEST']._serialized_start=146
  _globals['_CREATEPLANREQUEST']._serialized_end=316
# @@protoc_insertion_point(module_scope)
