# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/SubscriptionRequests.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n proto/SubscriptionRequests.proto\"x\n\x19\x43reateSubscriptionRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0c\n\x04plan\x18\x02 \x01(\t\x12\x0f\n\x07\x66\x65\x65Type\x18\x03 \x01(\t\x12\x15\n\rpaymentMethod\x18\x04 \x01(\t\x12\x13\n\x0binitialDate\x18\x05 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.SubscriptionRequests_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CREATESUBSCRIPTIONREQUEST']._serialized_start=36
  _globals['_CREATESUBSCRIPTIONREQUEST']._serialized_end=156
# @@protoc_insertion_point(module_scope)
