# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/UserRequests.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18proto/UserRequests.proto\"x\n\x19\x43reateSubscriptionRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0c\n\x04plan\x18\x02 \x01(\t\x12\x0f\n\x07\x66\x65\x65Type\x18\x03 \x01(\t\x12\x15\n\rpaymentMethod\x18\x04 \x01(\t\x12\x13\n\x0binitialDate\x18\x05 \x01(\t\"\xed\x01\n\x11\x43reateUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x19\n\x11\x63itizenCardNumber\x18\x04 \x01(\t\x12\x10\n\x08\x62irthday\x18\x05 \x01(\t\x12\x13\n\x0bphoneNumber\x18\x06 \x01(\t\x12\x0b\n\x03sex\x18\x07 \x01(\t\x12\x0c\n\x04role\x18\x08 \x01(\t\x12\x0c\n\x04plan\x18\t \x01(\t\x12\x0f\n\x07\x66\x65\x65Type\x18\n \x01(\t\x12\x15\n\rpaymentMethod\x18\x0b \x01(\t\x12\x13\n\x0binitialDate\x18\x0c \x01(\t\"1\n\x0b\x41uthRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.UserRequests_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CREATESUBSCRIPTIONREQUEST']._serialized_start=28
  _globals['_CREATESUBSCRIPTIONREQUEST']._serialized_end=148
  _globals['_CREATEUSERREQUEST']._serialized_start=151
  _globals['_CREATEUSERREQUEST']._serialized_end=388
  _globals['_AUTHREQUEST']._serialized_start=390
  _globals['_AUTHREQUEST']._serialized_end=439
# @@protoc_insertion_point(module_scope)
