@startuml

'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0
hide circle
hide methods
!theme toy

skinparam backgroundColor Transparent


skinparam Class {
Shadowing true
backgroundColor #6A9EFF
FontStyle bold
}

class Plan {
    id
    name
    description
    numberMinutes
    maxNumberDevices
    musicCollections
    musicSuggestions
    monthlyFee
    annualFee
    isActive
}

class Subscription{
    id
    initialDate
    isActive
    finalDate
    feeType
    isRenewed
    paymentMethod
    endSubscriptionDate
}




class AuthorityRole {
    authority
}

class User {
    username
    password
    id
    name
    citizenCardNumber
    birthday
    phoneNumber
    sex
}

Plan "1" -right-  "*..1" Subscription:contains <

AuthorityRole "1" -left- "*..1" User:has <
User "1" -down-  "*..1"Subscription:manages/contains >



@enduml
