// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SubscriptionRequests.proto

package com.example.sisdi_subscriptions.subscriptionmanagement.api.proto;

public final class SubscriptionRequests {
  private SubscriptionRequests() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CreateSubscriptionRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:example.CreateSubscriptionRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string username = 1;</code>
     * @return The username.
     */
    java.lang.String getUsername();
    /**
     * <code>string username = 1;</code>
     * @return The bytes for username.
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    /**
     * <code>string plan = 2;</code>
     * @return The plan.
     */
    java.lang.String getPlan();
    /**
     * <code>string plan = 2;</code>
     * @return The bytes for plan.
     */
    com.google.protobuf.ByteString
        getPlanBytes();

    /**
     * <code>string feeType = 3;</code>
     * @return The feeType.
     */
    java.lang.String getFeeType();
    /**
     * <code>string feeType = 3;</code>
     * @return The bytes for feeType.
     */
    com.google.protobuf.ByteString
        getFeeTypeBytes();

    /**
     * <code>string paymentMethod = 4;</code>
     * @return The paymentMethod.
     */
    java.lang.String getPaymentMethod();
    /**
     * <code>string paymentMethod = 4;</code>
     * @return The bytes for paymentMethod.
     */
    com.google.protobuf.ByteString
        getPaymentMethodBytes();

    /**
     * <code>string initialDate = 5;</code>
     * @return The initialDate.
     */
    java.lang.String getInitialDate();
    /**
     * <code>string initialDate = 5;</code>
     * @return The bytes for initialDate.
     */
    com.google.protobuf.ByteString
        getInitialDateBytes();
  }
  /**
   * Protobuf type {@code example.CreateSubscriptionRequest}
   */
  public static final class CreateSubscriptionRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:example.CreateSubscriptionRequest)
      CreateSubscriptionRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CreateSubscriptionRequest.newBuilder() to construct.
    private CreateSubscriptionRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CreateSubscriptionRequest() {
      username_ = "";
      plan_ = "";
      feeType_ = "";
      paymentMethod_ = "";
      initialDate_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CreateSubscriptionRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.internal_static_example_CreateSubscriptionRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.internal_static_example_CreateSubscriptionRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.CreateSubscriptionRequest.class, com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.CreateSubscriptionRequest.Builder.class);
    }

    public static final int USERNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object username_;
    /**
     * <code>string username = 1;</code>
     * @return The username.
     */
    @java.lang.Override
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      }
    }
    /**
     * <code>string username = 1;</code>
     * @return The bytes for username.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLAN_FIELD_NUMBER = 2;
    private volatile java.lang.Object plan_;
    /**
     * <code>string plan = 2;</code>
     * @return The plan.
     */
    @java.lang.Override
    public java.lang.String getPlan() {
      java.lang.Object ref = plan_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        plan_ = s;
        return s;
      }
    }
    /**
     * <code>string plan = 2;</code>
     * @return The bytes for plan.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPlanBytes() {
      java.lang.Object ref = plan_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        plan_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FEETYPE_FIELD_NUMBER = 3;
    private volatile java.lang.Object feeType_;
    /**
     * <code>string feeType = 3;</code>
     * @return The feeType.
     */
    @java.lang.Override
    public java.lang.String getFeeType() {
      java.lang.Object ref = feeType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        feeType_ = s;
        return s;
      }
    }
    /**
     * <code>string feeType = 3;</code>
     * @return The bytes for feeType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFeeTypeBytes() {
      java.lang.Object ref = feeType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        feeType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAYMENTMETHOD_FIELD_NUMBER = 4;
    private volatile java.lang.Object paymentMethod_;
    /**
     * <code>string paymentMethod = 4;</code>
     * @return The paymentMethod.
     */
    @java.lang.Override
    public java.lang.String getPaymentMethod() {
      java.lang.Object ref = paymentMethod_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        paymentMethod_ = s;
        return s;
      }
    }
    /**
     * <code>string paymentMethod = 4;</code>
     * @return The bytes for paymentMethod.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPaymentMethodBytes() {
      java.lang.Object ref = paymentMethod_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        paymentMethod_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INITIALDATE_FIELD_NUMBER = 5;
    private volatile java.lang.Object initialDate_;
    /**
     * <code>string initialDate = 5;</code>
     * @return The initialDate.
     */
    @java.lang.Override
    public java.lang.String getInitialDate() {
      java.lang.Object ref = initialDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        initialDate_ = s;
        return s;
      }
    }
    /**
     * <code>string initialDate = 5;</code>
     * @return The bytes for initialDate.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getInitialDateBytes() {
      java.lang.Object ref = initialDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        initialDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(username_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, username_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(plan_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, plan_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(feeType_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, feeType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(paymentMethod_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, paymentMethod_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(initialDate_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, initialDate_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(username_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, username_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(plan_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, plan_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(feeType_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, feeType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(paymentMethod_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, paymentMethod_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(initialDate_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, initialDate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.CreateSubscriptionRequest)) {
        return super.equals(obj);
      }
      com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.CreateSubscriptionRequest other = (com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.CreateSubscriptionRequest) obj;

      if (!getUsername()
          .equals(other.getUsername())) return false;
      if (!getPlan()
          .equals(other.getPlan())) return false;
      if (!getFeeType()
          .equals(other.getFeeType())) return false;
      if (!getPaymentMethod()
          .equals(other.getPaymentMethod())) return false;
      if (!getInitialDate()
          .equals(other.getInitialDate())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUsername().hashCode();
      hash = (37 * hash) + PLAN_FIELD_NUMBER;
      hash = (53 * hash) + getPlan().hashCode();
      hash = (37 * hash) + FEETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getFeeType().hashCode();
      hash = (37 * hash) + PAYMENTMETHOD_FIELD_NUMBER;
      hash = (53 * hash) + getPaymentMethod().hashCode();
      hash = (37 * hash) + INITIALDATE_FIELD_NUMBER;
      hash = (53 * hash) + getInitialDate().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.CreateSubscriptionRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.CreateSubscriptionRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.CreateSubscriptionRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.CreateSubscriptionRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.CreateSubscriptionRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.CreateSubscriptionRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.CreateSubscriptionRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.CreateSubscriptionRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.CreateSubscriptionRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.CreateSubscriptionRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.CreateSubscriptionRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.CreateSubscriptionRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.CreateSubscriptionRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code example.CreateSubscriptionRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:example.CreateSubscriptionRequest)
        com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.CreateSubscriptionRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.internal_static_example_CreateSubscriptionRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.internal_static_example_CreateSubscriptionRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.CreateSubscriptionRequest.class, com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.CreateSubscriptionRequest.Builder.class);
      }

      // Construct using com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.CreateSubscriptionRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        username_ = "";

        plan_ = "";

        feeType_ = "";

        paymentMethod_ = "";

        initialDate_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.internal_static_example_CreateSubscriptionRequest_descriptor;
      }

      @java.lang.Override
      public com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.CreateSubscriptionRequest getDefaultInstanceForType() {
        return com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.CreateSubscriptionRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.CreateSubscriptionRequest build() {
        com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.CreateSubscriptionRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.CreateSubscriptionRequest buildPartial() {
        com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.CreateSubscriptionRequest result = new com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.CreateSubscriptionRequest(this);
        result.username_ = username_;
        result.plan_ = plan_;
        result.feeType_ = feeType_;
        result.paymentMethod_ = paymentMethod_;
        result.initialDate_ = initialDate_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.CreateSubscriptionRequest) {
          return mergeFrom((com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.CreateSubscriptionRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.CreateSubscriptionRequest other) {
        if (other == com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.CreateSubscriptionRequest.getDefaultInstance()) return this;
        if (!other.getUsername().isEmpty()) {
          username_ = other.username_;
          onChanged();
        }
        if (!other.getPlan().isEmpty()) {
          plan_ = other.plan_;
          onChanged();
        }
        if (!other.getFeeType().isEmpty()) {
          feeType_ = other.feeType_;
          onChanged();
        }
        if (!other.getPaymentMethod().isEmpty()) {
          paymentMethod_ = other.paymentMethod_;
          onChanged();
        }
        if (!other.getInitialDate().isEmpty()) {
          initialDate_ = other.initialDate_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                username_ = input.readStringRequireUtf8();

                break;
              } // case 10
              case 18: {
                plan_ = input.readStringRequireUtf8();

                break;
              } // case 18
              case 26: {
                feeType_ = input.readStringRequireUtf8();

                break;
              } // case 26
              case 34: {
                paymentMethod_ = input.readStringRequireUtf8();

                break;
              } // case 34
              case 42: {
                initialDate_ = input.readStringRequireUtf8();

                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private java.lang.Object username_ = "";
      /**
       * <code>string username = 1;</code>
       * @return The username.
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string username = 1;</code>
       * @return The bytes for username.
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string username = 1;</code>
       * @param value The username to set.
       * @return This builder for chaining.
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string username = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUsername() {
        
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <code>string username = 1;</code>
       * @param value The bytes for username to set.
       * @return This builder for chaining.
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        username_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object plan_ = "";
      /**
       * <code>string plan = 2;</code>
       * @return The plan.
       */
      public java.lang.String getPlan() {
        java.lang.Object ref = plan_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          plan_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string plan = 2;</code>
       * @return The bytes for plan.
       */
      public com.google.protobuf.ByteString
          getPlanBytes() {
        java.lang.Object ref = plan_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          plan_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string plan = 2;</code>
       * @param value The plan to set.
       * @return This builder for chaining.
       */
      public Builder setPlan(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        plan_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string plan = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlan() {
        
        plan_ = getDefaultInstance().getPlan();
        onChanged();
        return this;
      }
      /**
       * <code>string plan = 2;</code>
       * @param value The bytes for plan to set.
       * @return This builder for chaining.
       */
      public Builder setPlanBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        plan_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object feeType_ = "";
      /**
       * <code>string feeType = 3;</code>
       * @return The feeType.
       */
      public java.lang.String getFeeType() {
        java.lang.Object ref = feeType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          feeType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string feeType = 3;</code>
       * @return The bytes for feeType.
       */
      public com.google.protobuf.ByteString
          getFeeTypeBytes() {
        java.lang.Object ref = feeType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          feeType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string feeType = 3;</code>
       * @param value The feeType to set.
       * @return This builder for chaining.
       */
      public Builder setFeeType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        feeType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string feeType = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFeeType() {
        
        feeType_ = getDefaultInstance().getFeeType();
        onChanged();
        return this;
      }
      /**
       * <code>string feeType = 3;</code>
       * @param value The bytes for feeType to set.
       * @return This builder for chaining.
       */
      public Builder setFeeTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        feeType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object paymentMethod_ = "";
      /**
       * <code>string paymentMethod = 4;</code>
       * @return The paymentMethod.
       */
      public java.lang.String getPaymentMethod() {
        java.lang.Object ref = paymentMethod_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          paymentMethod_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string paymentMethod = 4;</code>
       * @return The bytes for paymentMethod.
       */
      public com.google.protobuf.ByteString
          getPaymentMethodBytes() {
        java.lang.Object ref = paymentMethod_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          paymentMethod_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string paymentMethod = 4;</code>
       * @param value The paymentMethod to set.
       * @return This builder for chaining.
       */
      public Builder setPaymentMethod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        paymentMethod_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string paymentMethod = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPaymentMethod() {
        
        paymentMethod_ = getDefaultInstance().getPaymentMethod();
        onChanged();
        return this;
      }
      /**
       * <code>string paymentMethod = 4;</code>
       * @param value The bytes for paymentMethod to set.
       * @return This builder for chaining.
       */
      public Builder setPaymentMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        paymentMethod_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object initialDate_ = "";
      /**
       * <code>string initialDate = 5;</code>
       * @return The initialDate.
       */
      public java.lang.String getInitialDate() {
        java.lang.Object ref = initialDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          initialDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string initialDate = 5;</code>
       * @return The bytes for initialDate.
       */
      public com.google.protobuf.ByteString
          getInitialDateBytes() {
        java.lang.Object ref = initialDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          initialDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string initialDate = 5;</code>
       * @param value The initialDate to set.
       * @return This builder for chaining.
       */
      public Builder setInitialDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        initialDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string initialDate = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearInitialDate() {
        
        initialDate_ = getDefaultInstance().getInitialDate();
        onChanged();
        return this;
      }
      /**
       * <code>string initialDate = 5;</code>
       * @param value The bytes for initialDate to set.
       * @return This builder for chaining.
       */
      public Builder setInitialDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        initialDate_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:example.CreateSubscriptionRequest)
    }

    // @@protoc_insertion_point(class_scope:example.CreateSubscriptionRequest)
    private static final com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.CreateSubscriptionRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.CreateSubscriptionRequest();
    }

    public static com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.CreateSubscriptionRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CreateSubscriptionRequest>
        PARSER = new com.google.protobuf.AbstractParser<CreateSubscriptionRequest>() {
      @java.lang.Override
      public CreateSubscriptionRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CreateSubscriptionRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CreateSubscriptionRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.sisdi_subscriptions.subscriptionmanagement.api.proto.SubscriptionRequests.CreateSubscriptionRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_CreateSubscriptionRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_example_CreateSubscriptionRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032SubscriptionRequests.proto\022\007example\"x\n" +
      "\031CreateSubscriptionRequest\022\020\n\010username\030\001" +
      " \001(\t\022\014\n\004plan\030\002 \001(\t\022\017\n\007feeType\030\003 \001(\t\022\025\n\rp" +
      "aymentMethod\030\004 \001(\t\022\023\n\013initialDate\030\005 \001(\tB" +
      "B\n@com.example.sisdi_subscriptions.subsc" +
      "riptionmanagement.api.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_example_CreateSubscriptionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_example_CreateSubscriptionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_example_CreateSubscriptionRequest_descriptor,
        new java.lang.String[] { "Username", "Plan", "FeeType", "PaymentMethod", "InitialDate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
