// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlanEntity.proto

package com.example.sisdi_plans.planmanagement.model.proto;

public final class PlanEntity {
  private PlanEntity() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlanOrBuilder extends
      // @@protoc_insertion_point(interface_extends:example.Plan)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string description = 2;</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 2;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>int32 numberOfMinutes = 3;</code>
     * @return The numberOfMinutes.
     */
    int getNumberOfMinutes();

    /**
     * <code>int32 musicCollections = 4;</code>
     * @return The musicCollections.
     */
    int getMusicCollections();

    /**
     * <code>int64 monthlyFee = 5;</code>
     * @return The monthlyFee.
     */
    long getMonthlyFee();

    /**
     * <code>int64 annualFee = 6;</code>
     * @return The annualFee.
     */
    long getAnnualFee();

    /**
     * <code>bool isActive = 7;</code>
     * @return The isActive.
     */
    boolean getIsActive();
  }
  /**
   * Protobuf type {@code example.Plan}
   */
  public static final class Plan extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:example.Plan)
      PlanOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Plan.newBuilder() to construct.
    private Plan(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Plan() {
      name_ = "";
      description_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Plan();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.internal_static_example_Plan_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.internal_static_example_Plan_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan.class, com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan.Builder.class);
    }

    /**
     * Protobuf enum {@code example.Plan.MusicSuggestions}
     */
    public enum MusicSuggestions
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>AUTOMATIC = 0;</code>
       */
      AUTOMATIC(0),
      /**
       * <code>PERSONALIZED = 1;</code>
       */
      PERSONALIZED(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>AUTOMATIC = 0;</code>
       */
      public static final int AUTOMATIC_VALUE = 0;
      /**
       * <code>PERSONALIZED = 1;</code>
       */
      public static final int PERSONALIZED_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MusicSuggestions valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static MusicSuggestions forNumber(int value) {
        switch (value) {
          case 0: return AUTOMATIC;
          case 1: return PERSONALIZED;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MusicSuggestions>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MusicSuggestions> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MusicSuggestions>() {
              public MusicSuggestions findValueByNumber(int number) {
                return MusicSuggestions.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan.getDescriptor().getEnumTypes().get(0);
      }

      private static final MusicSuggestions[] VALUES = values();

      public static MusicSuggestions valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MusicSuggestions(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:example.Plan.MusicSuggestions)
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 2;
    private volatile java.lang.Object description_;
    /**
     * <code>string description = 2;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 2;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NUMBEROFMINUTES_FIELD_NUMBER = 3;
    private int numberOfMinutes_;
    /**
     * <code>int32 numberOfMinutes = 3;</code>
     * @return The numberOfMinutes.
     */
    @java.lang.Override
    public int getNumberOfMinutes() {
      return numberOfMinutes_;
    }

    public static final int MUSICCOLLECTIONS_FIELD_NUMBER = 4;
    private int musicCollections_;
    /**
     * <code>int32 musicCollections = 4;</code>
     * @return The musicCollections.
     */
    @java.lang.Override
    public int getMusicCollections() {
      return musicCollections_;
    }

    public static final int MONTHLYFEE_FIELD_NUMBER = 5;
    private long monthlyFee_;
    /**
     * <code>int64 monthlyFee = 5;</code>
     * @return The monthlyFee.
     */
    @java.lang.Override
    public long getMonthlyFee() {
      return monthlyFee_;
    }

    public static final int ANNUALFEE_FIELD_NUMBER = 6;
    private long annualFee_;
    /**
     * <code>int64 annualFee = 6;</code>
     * @return The annualFee.
     */
    @java.lang.Override
    public long getAnnualFee() {
      return annualFee_;
    }

    public static final int ISACTIVE_FIELD_NUMBER = 7;
    private boolean isActive_;
    /**
     * <code>bool isActive = 7;</code>
     * @return The isActive.
     */
    @java.lang.Override
    public boolean getIsActive() {
      return isActive_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, description_);
      }
      if (numberOfMinutes_ != 0) {
        output.writeInt32(3, numberOfMinutes_);
      }
      if (musicCollections_ != 0) {
        output.writeInt32(4, musicCollections_);
      }
      if (monthlyFee_ != 0L) {
        output.writeInt64(5, monthlyFee_);
      }
      if (annualFee_ != 0L) {
        output.writeInt64(6, annualFee_);
      }
      if (isActive_ != false) {
        output.writeBool(7, isActive_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, description_);
      }
      if (numberOfMinutes_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, numberOfMinutes_);
      }
      if (musicCollections_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, musicCollections_);
      }
      if (monthlyFee_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, monthlyFee_);
      }
      if (annualFee_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, annualFee_);
      }
      if (isActive_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, isActive_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan)) {
        return super.equals(obj);
      }
      com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan other = (com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getDescription()
          .equals(other.getDescription())) return false;
      if (getNumberOfMinutes()
          != other.getNumberOfMinutes()) return false;
      if (getMusicCollections()
          != other.getMusicCollections()) return false;
      if (getMonthlyFee()
          != other.getMonthlyFee()) return false;
      if (getAnnualFee()
          != other.getAnnualFee()) return false;
      if (getIsActive()
          != other.getIsActive()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (37 * hash) + NUMBEROFMINUTES_FIELD_NUMBER;
      hash = (53 * hash) + getNumberOfMinutes();
      hash = (37 * hash) + MUSICCOLLECTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getMusicCollections();
      hash = (37 * hash) + MONTHLYFEE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMonthlyFee());
      hash = (37 * hash) + ANNUALFEE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAnnualFee());
      hash = (37 * hash) + ISACTIVE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsActive());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code example.Plan}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:example.Plan)
        com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.internal_static_example_Plan_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.internal_static_example_Plan_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan.class, com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan.Builder.class);
      }

      // Construct using com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        description_ = "";

        numberOfMinutes_ = 0;

        musicCollections_ = 0;

        monthlyFee_ = 0L;

        annualFee_ = 0L;

        isActive_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.internal_static_example_Plan_descriptor;
      }

      @java.lang.Override
      public com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan getDefaultInstanceForType() {
        return com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan build() {
        com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan buildPartial() {
        com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan result = new com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan(this);
        result.name_ = name_;
        result.description_ = description_;
        result.numberOfMinutes_ = numberOfMinutes_;
        result.musicCollections_ = musicCollections_;
        result.monthlyFee_ = monthlyFee_;
        result.annualFee_ = annualFee_;
        result.isActive_ = isActive_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan) {
          return mergeFrom((com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan other) {
        if (other == com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        if (other.getNumberOfMinutes() != 0) {
          setNumberOfMinutes(other.getNumberOfMinutes());
        }
        if (other.getMusicCollections() != 0) {
          setMusicCollections(other.getMusicCollections());
        }
        if (other.getMonthlyFee() != 0L) {
          setMonthlyFee(other.getMonthlyFee());
        }
        if (other.getAnnualFee() != 0L) {
          setAnnualFee(other.getAnnualFee());
        }
        if (other.getIsActive() != false) {
          setIsActive(other.getIsActive());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                name_ = input.readStringRequireUtf8();

                break;
              } // case 10
              case 18: {
                description_ = input.readStringRequireUtf8();

                break;
              } // case 18
              case 24: {
                numberOfMinutes_ = input.readInt32();

                break;
              } // case 24
              case 32: {
                musicCollections_ = input.readInt32();

                break;
              } // case 32
              case 40: {
                monthlyFee_ = input.readInt64();

                break;
              } // case 40
              case 48: {
                annualFee_ = input.readInt64();

                break;
              } // case 48
              case 56: {
                isActive_ = input.readBool();

                break;
              } // case 56
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 2;</code>
       * @return The description.
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 2;</code>
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 2;</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string description = 2;</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }

      private int numberOfMinutes_ ;
      /**
       * <code>int32 numberOfMinutes = 3;</code>
       * @return The numberOfMinutes.
       */
      @java.lang.Override
      public int getNumberOfMinutes() {
        return numberOfMinutes_;
      }
      /**
       * <code>int32 numberOfMinutes = 3;</code>
       * @param value The numberOfMinutes to set.
       * @return This builder for chaining.
       */
      public Builder setNumberOfMinutes(int value) {
        
        numberOfMinutes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 numberOfMinutes = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumberOfMinutes() {
        
        numberOfMinutes_ = 0;
        onChanged();
        return this;
      }

      private int musicCollections_ ;
      /**
       * <code>int32 musicCollections = 4;</code>
       * @return The musicCollections.
       */
      @java.lang.Override
      public int getMusicCollections() {
        return musicCollections_;
      }
      /**
       * <code>int32 musicCollections = 4;</code>
       * @param value The musicCollections to set.
       * @return This builder for chaining.
       */
      public Builder setMusicCollections(int value) {
        
        musicCollections_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 musicCollections = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMusicCollections() {
        
        musicCollections_ = 0;
        onChanged();
        return this;
      }

      private long monthlyFee_ ;
      /**
       * <code>int64 monthlyFee = 5;</code>
       * @return The monthlyFee.
       */
      @java.lang.Override
      public long getMonthlyFee() {
        return monthlyFee_;
      }
      /**
       * <code>int64 monthlyFee = 5;</code>
       * @param value The monthlyFee to set.
       * @return This builder for chaining.
       */
      public Builder setMonthlyFee(long value) {
        
        monthlyFee_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 monthlyFee = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearMonthlyFee() {
        
        monthlyFee_ = 0L;
        onChanged();
        return this;
      }

      private long annualFee_ ;
      /**
       * <code>int64 annualFee = 6;</code>
       * @return The annualFee.
       */
      @java.lang.Override
      public long getAnnualFee() {
        return annualFee_;
      }
      /**
       * <code>int64 annualFee = 6;</code>
       * @param value The annualFee to set.
       * @return This builder for chaining.
       */
      public Builder setAnnualFee(long value) {
        
        annualFee_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 annualFee = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearAnnualFee() {
        
        annualFee_ = 0L;
        onChanged();
        return this;
      }

      private boolean isActive_ ;
      /**
       * <code>bool isActive = 7;</code>
       * @return The isActive.
       */
      @java.lang.Override
      public boolean getIsActive() {
        return isActive_;
      }
      /**
       * <code>bool isActive = 7;</code>
       * @param value The isActive to set.
       * @return This builder for chaining.
       */
      public Builder setIsActive(boolean value) {
        
        isActive_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isActive = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsActive() {
        
        isActive_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:example.Plan)
    }

    // @@protoc_insertion_point(class_scope:example.Plan)
    private static final com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan();
    }

    public static com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Plan>
        PARSER = new com.google.protobuf.AbstractParser<Plan>() {
      @java.lang.Override
      public Plan parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Plan> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Plan> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PlanListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:example.PlanList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .example.Plan plan = 1;</code>
     */
    java.util.List<com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan> 
        getPlanList();
    /**
     * <code>repeated .example.Plan plan = 1;</code>
     */
    com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan getPlan(int index);
    /**
     * <code>repeated .example.Plan plan = 1;</code>
     */
    int getPlanCount();
    /**
     * <code>repeated .example.Plan plan = 1;</code>
     */
    java.util.List<? extends com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanOrBuilder> 
        getPlanOrBuilderList();
    /**
     * <code>repeated .example.Plan plan = 1;</code>
     */
    com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanOrBuilder getPlanOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code example.PlanList}
   */
  public static final class PlanList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:example.PlanList)
      PlanListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlanList.newBuilder() to construct.
    private PlanList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlanList() {
      plan_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PlanList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.internal_static_example_PlanList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.internal_static_example_PlanList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanList.class, com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanList.Builder.class);
    }

    public static final int PLAN_FIELD_NUMBER = 1;
    private java.util.List<com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan> plan_;
    /**
     * <code>repeated .example.Plan plan = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan> getPlanList() {
      return plan_;
    }
    /**
     * <code>repeated .example.Plan plan = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanOrBuilder> 
        getPlanOrBuilderList() {
      return plan_;
    }
    /**
     * <code>repeated .example.Plan plan = 1;</code>
     */
    @java.lang.Override
    public int getPlanCount() {
      return plan_.size();
    }
    /**
     * <code>repeated .example.Plan plan = 1;</code>
     */
    @java.lang.Override
    public com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan getPlan(int index) {
      return plan_.get(index);
    }
    /**
     * <code>repeated .example.Plan plan = 1;</code>
     */
    @java.lang.Override
    public com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanOrBuilder getPlanOrBuilder(
        int index) {
      return plan_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < plan_.size(); i++) {
        output.writeMessage(1, plan_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < plan_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, plan_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanList)) {
        return super.equals(obj);
      }
      com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanList other = (com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanList) obj;

      if (!getPlanList()
          .equals(other.getPlanList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPlanCount() > 0) {
        hash = (37 * hash) + PLAN_FIELD_NUMBER;
        hash = (53 * hash) + getPlanList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code example.PlanList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:example.PlanList)
        com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.internal_static_example_PlanList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.internal_static_example_PlanList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanList.class, com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanList.Builder.class);
      }

      // Construct using com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanList.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (planBuilder_ == null) {
          plan_ = java.util.Collections.emptyList();
        } else {
          plan_ = null;
          planBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.internal_static_example_PlanList_descriptor;
      }

      @java.lang.Override
      public com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanList getDefaultInstanceForType() {
        return com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanList.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanList build() {
        com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanList buildPartial() {
        com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanList result = new com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanList(this);
        int from_bitField0_ = bitField0_;
        if (planBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            plan_ = java.util.Collections.unmodifiableList(plan_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.plan_ = plan_;
        } else {
          result.plan_ = planBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanList) {
          return mergeFrom((com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanList other) {
        if (other == com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanList.getDefaultInstance()) return this;
        if (planBuilder_ == null) {
          if (!other.plan_.isEmpty()) {
            if (plan_.isEmpty()) {
              plan_ = other.plan_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePlanIsMutable();
              plan_.addAll(other.plan_);
            }
            onChanged();
          }
        } else {
          if (!other.plan_.isEmpty()) {
            if (planBuilder_.isEmpty()) {
              planBuilder_.dispose();
              planBuilder_ = null;
              plan_ = other.plan_;
              bitField0_ = (bitField0_ & ~0x00000001);
              planBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPlanFieldBuilder() : null;
            } else {
              planBuilder_.addAllMessages(other.plan_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan m =
                    input.readMessage(
                        com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan.parser(),
                        extensionRegistry);
                if (planBuilder_ == null) {
                  ensurePlanIsMutable();
                  plan_.add(m);
                } else {
                  planBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan> plan_ =
        java.util.Collections.emptyList();
      private void ensurePlanIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          plan_ = new java.util.ArrayList<com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan>(plan_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan, com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan.Builder, com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanOrBuilder> planBuilder_;

      /**
       * <code>repeated .example.Plan plan = 1;</code>
       */
      public java.util.List<com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan> getPlanList() {
        if (planBuilder_ == null) {
          return java.util.Collections.unmodifiableList(plan_);
        } else {
          return planBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .example.Plan plan = 1;</code>
       */
      public int getPlanCount() {
        if (planBuilder_ == null) {
          return plan_.size();
        } else {
          return planBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .example.Plan plan = 1;</code>
       */
      public com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan getPlan(int index) {
        if (planBuilder_ == null) {
          return plan_.get(index);
        } else {
          return planBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .example.Plan plan = 1;</code>
       */
      public Builder setPlan(
          int index, com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan value) {
        if (planBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlanIsMutable();
          plan_.set(index, value);
          onChanged();
        } else {
          planBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .example.Plan plan = 1;</code>
       */
      public Builder setPlan(
          int index, com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan.Builder builderForValue) {
        if (planBuilder_ == null) {
          ensurePlanIsMutable();
          plan_.set(index, builderForValue.build());
          onChanged();
        } else {
          planBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .example.Plan plan = 1;</code>
       */
      public Builder addPlan(com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan value) {
        if (planBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlanIsMutable();
          plan_.add(value);
          onChanged();
        } else {
          planBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .example.Plan plan = 1;</code>
       */
      public Builder addPlan(
          int index, com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan value) {
        if (planBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlanIsMutable();
          plan_.add(index, value);
          onChanged();
        } else {
          planBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .example.Plan plan = 1;</code>
       */
      public Builder addPlan(
          com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan.Builder builderForValue) {
        if (planBuilder_ == null) {
          ensurePlanIsMutable();
          plan_.add(builderForValue.build());
          onChanged();
        } else {
          planBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .example.Plan plan = 1;</code>
       */
      public Builder addPlan(
          int index, com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan.Builder builderForValue) {
        if (planBuilder_ == null) {
          ensurePlanIsMutable();
          plan_.add(index, builderForValue.build());
          onChanged();
        } else {
          planBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .example.Plan plan = 1;</code>
       */
      public Builder addAllPlan(
          java.lang.Iterable<? extends com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan> values) {
        if (planBuilder_ == null) {
          ensurePlanIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, plan_);
          onChanged();
        } else {
          planBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .example.Plan plan = 1;</code>
       */
      public Builder clearPlan() {
        if (planBuilder_ == null) {
          plan_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          planBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .example.Plan plan = 1;</code>
       */
      public Builder removePlan(int index) {
        if (planBuilder_ == null) {
          ensurePlanIsMutable();
          plan_.remove(index);
          onChanged();
        } else {
          planBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .example.Plan plan = 1;</code>
       */
      public com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan.Builder getPlanBuilder(
          int index) {
        return getPlanFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .example.Plan plan = 1;</code>
       */
      public com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanOrBuilder getPlanOrBuilder(
          int index) {
        if (planBuilder_ == null) {
          return plan_.get(index);  } else {
          return planBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .example.Plan plan = 1;</code>
       */
      public java.util.List<? extends com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanOrBuilder> 
           getPlanOrBuilderList() {
        if (planBuilder_ != null) {
          return planBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(plan_);
        }
      }
      /**
       * <code>repeated .example.Plan plan = 1;</code>
       */
      public com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan.Builder addPlanBuilder() {
        return getPlanFieldBuilder().addBuilder(
            com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan.getDefaultInstance());
      }
      /**
       * <code>repeated .example.Plan plan = 1;</code>
       */
      public com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan.Builder addPlanBuilder(
          int index) {
        return getPlanFieldBuilder().addBuilder(
            index, com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan.getDefaultInstance());
      }
      /**
       * <code>repeated .example.Plan plan = 1;</code>
       */
      public java.util.List<com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan.Builder> 
           getPlanBuilderList() {
        return getPlanFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan, com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan.Builder, com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanOrBuilder> 
          getPlanFieldBuilder() {
        if (planBuilder_ == null) {
          planBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan, com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.Plan.Builder, com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanOrBuilder>(
                  plan_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          plan_ = null;
        }
        return planBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:example.PlanList)
    }

    // @@protoc_insertion_point(class_scope:example.PlanList)
    private static final com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanList();
    }

    public static com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlanList>
        PARSER = new com.google.protobuf.AbstractParser<PlanList>() {
      @java.lang.Override
      public PlanList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PlanList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlanList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.sisdi_plans.planmanagement.model.proto.PlanEntity.PlanList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_Plan_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_example_Plan_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_PlanList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_example_PlanList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020PlanEntity.proto\022\007example\"\312\001\n\004Plan\022\014\n\004" +
      "name\030\001 \001(\t\022\023\n\013description\030\002 \001(\t\022\027\n\017numbe" +
      "rOfMinutes\030\003 \001(\005\022\030\n\020musicCollections\030\004 \001" +
      "(\005\022\022\n\nmonthlyFee\030\005 \001(\003\022\021\n\tannualFee\030\006 \001(" +
      "\003\022\020\n\010isActive\030\007 \001(\010\"3\n\020MusicSuggestions\022" +
      "\r\n\tAUTOMATIC\020\000\022\020\n\014PERSONALIZED\020\001\"\'\n\010Plan" +
      "List\022\033\n\004plan\030\001 \003(\0132\r.example.PlanB4\n2com" +
      ".example.sisdi_plans.planmanagement.mode" +
      "l.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_example_Plan_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_example_Plan_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_example_Plan_descriptor,
        new java.lang.String[] { "Name", "Description", "NumberOfMinutes", "MusicCollections", "MonthlyFee", "AnnualFee", "IsActive", });
    internal_static_example_PlanList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_example_PlanList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_example_PlanList_descriptor,
        new java.lang.String[] { "Plan", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
