// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SubscriptionEntity.proto

package com.example.sisdi_subscriptions.subscriptionmanagement.model.proto;

public final class SubscriptionEntity {
  private SubscriptionEntity() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SubscriptionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:example.Subscription)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string subscriberID = 1;</code>
     * @return The subscriberID.
     */
    java.lang.String getSubscriberID();
    /**
     * <code>string subscriberID = 1;</code>
     * @return The bytes for subscriberID.
     */
    com.google.protobuf.ByteString
        getSubscriberIDBytes();

    /**
     * <code>string plan = 2;</code>
     * @return The plan.
     */
    java.lang.String getPlan();
    /**
     * <code>string plan = 2;</code>
     * @return The bytes for plan.
     */
    com.google.protobuf.ByteString
        getPlanBytes();

    /**
     * <code>string initialDate = 3;</code>
     * @return The initialDate.
     */
    java.lang.String getInitialDate();
    /**
     * <code>string initialDate = 3;</code>
     * @return The bytes for initialDate.
     */
    com.google.protobuf.ByteString
        getInitialDateBytes();

    /**
     * <code>bool isActive = 4;</code>
     * @return The isActive.
     */
    boolean getIsActive();

    /**
     * <code>string finalDate = 5;</code>
     * @return The finalDate.
     */
    java.lang.String getFinalDate();
    /**
     * <code>string finalDate = 5;</code>
     * @return The bytes for finalDate.
     */
    com.google.protobuf.ByteString
        getFinalDateBytes();

    /**
     * <code>string endSubscriptionDate = 6;</code>
     * @return The endSubscriptionDate.
     */
    java.lang.String getEndSubscriptionDate();
    /**
     * <code>string endSubscriptionDate = 6;</code>
     * @return The bytes for endSubscriptionDate.
     */
    com.google.protobuf.ByteString
        getEndSubscriptionDateBytes();

    /**
     * <code>.example.Subscription.FeeType feeType = 7;</code>
     * @return The enum numeric value on the wire for feeType.
     */
    int getFeeTypeValue();
    /**
     * <code>.example.Subscription.FeeType feeType = 7;</code>
     * @return The feeType.
     */
    com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.FeeType getFeeType();

    /**
     * <code>.example.Subscription.PaymentMethod paymentMethod = 8;</code>
     * @return The enum numeric value on the wire for paymentMethod.
     */
    int getPaymentMethodValue();
    /**
     * <code>.example.Subscription.PaymentMethod paymentMethod = 8;</code>
     * @return The paymentMethod.
     */
    com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.PaymentMethod getPaymentMethod();
  }
  /**
   * Protobuf type {@code example.Subscription}
   */
  public static final class Subscription extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:example.Subscription)
      SubscriptionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Subscription.newBuilder() to construct.
    private Subscription(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Subscription() {
      subscriberID_ = "";
      plan_ = "";
      initialDate_ = "";
      finalDate_ = "";
      endSubscriptionDate_ = "";
      feeType_ = 0;
      paymentMethod_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Subscription();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.internal_static_example_Subscription_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.internal_static_example_Subscription_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.class, com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.Builder.class);
    }

    /**
     * Protobuf enum {@code example.Subscription.FeeType}
     */
    public enum FeeType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>FEE_TYPE_NA = 0;</code>
       */
      FEE_TYPE_NA(0),
      /**
       * <code>MONTHLY = 1;</code>
       */
      MONTHLY(1),
      /**
       * <code>ANNUAL = 2;</code>
       */
      ANNUAL(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>FEE_TYPE_NA = 0;</code>
       */
      public static final int FEE_TYPE_NA_VALUE = 0;
      /**
       * <code>MONTHLY = 1;</code>
       */
      public static final int MONTHLY_VALUE = 1;
      /**
       * <code>ANNUAL = 2;</code>
       */
      public static final int ANNUAL_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static FeeType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static FeeType forNumber(int value) {
        switch (value) {
          case 0: return FEE_TYPE_NA;
          case 1: return MONTHLY;
          case 2: return ANNUAL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<FeeType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          FeeType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<FeeType>() {
              public FeeType findValueByNumber(int number) {
                return FeeType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.getDescriptor().getEnumTypes().get(0);
      }

      private static final FeeType[] VALUES = values();

      public static FeeType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private FeeType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:example.Subscription.FeeType)
    }

    /**
     * Protobuf enum {@code example.Subscription.PaymentMethod}
     */
    public enum PaymentMethod
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PAYMENT_METHOD_NA = 0;</code>
       */
      PAYMENT_METHOD_NA(0),
      /**
       * <code>MBWAY = 1;</code>
       */
      MBWAY(1),
      /**
       * <code>CARD = 2;</code>
       */
      CARD(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>PAYMENT_METHOD_NA = 0;</code>
       */
      public static final int PAYMENT_METHOD_NA_VALUE = 0;
      /**
       * <code>MBWAY = 1;</code>
       */
      public static final int MBWAY_VALUE = 1;
      /**
       * <code>CARD = 2;</code>
       */
      public static final int CARD_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PaymentMethod valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static PaymentMethod forNumber(int value) {
        switch (value) {
          case 0: return PAYMENT_METHOD_NA;
          case 1: return MBWAY;
          case 2: return CARD;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PaymentMethod>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          PaymentMethod> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PaymentMethod>() {
              public PaymentMethod findValueByNumber(int number) {
                return PaymentMethod.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.getDescriptor().getEnumTypes().get(1);
      }

      private static final PaymentMethod[] VALUES = values();

      public static PaymentMethod valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private PaymentMethod(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:example.Subscription.PaymentMethod)
    }

    public static final int SUBSCRIBERID_FIELD_NUMBER = 1;
    private volatile java.lang.Object subscriberID_;
    /**
     * <code>string subscriberID = 1;</code>
     * @return The subscriberID.
     */
    @java.lang.Override
    public java.lang.String getSubscriberID() {
      java.lang.Object ref = subscriberID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        subscriberID_ = s;
        return s;
      }
    }
    /**
     * <code>string subscriberID = 1;</code>
     * @return The bytes for subscriberID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSubscriberIDBytes() {
      java.lang.Object ref = subscriberID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subscriberID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLAN_FIELD_NUMBER = 2;
    private volatile java.lang.Object plan_;
    /**
     * <code>string plan = 2;</code>
     * @return The plan.
     */
    @java.lang.Override
    public java.lang.String getPlan() {
      java.lang.Object ref = plan_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        plan_ = s;
        return s;
      }
    }
    /**
     * <code>string plan = 2;</code>
     * @return The bytes for plan.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPlanBytes() {
      java.lang.Object ref = plan_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        plan_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INITIALDATE_FIELD_NUMBER = 3;
    private volatile java.lang.Object initialDate_;
    /**
     * <code>string initialDate = 3;</code>
     * @return The initialDate.
     */
    @java.lang.Override
    public java.lang.String getInitialDate() {
      java.lang.Object ref = initialDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        initialDate_ = s;
        return s;
      }
    }
    /**
     * <code>string initialDate = 3;</code>
     * @return The bytes for initialDate.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getInitialDateBytes() {
      java.lang.Object ref = initialDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        initialDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISACTIVE_FIELD_NUMBER = 4;
    private boolean isActive_;
    /**
     * <code>bool isActive = 4;</code>
     * @return The isActive.
     */
    @java.lang.Override
    public boolean getIsActive() {
      return isActive_;
    }

    public static final int FINALDATE_FIELD_NUMBER = 5;
    private volatile java.lang.Object finalDate_;
    /**
     * <code>string finalDate = 5;</code>
     * @return The finalDate.
     */
    @java.lang.Override
    public java.lang.String getFinalDate() {
      java.lang.Object ref = finalDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        finalDate_ = s;
        return s;
      }
    }
    /**
     * <code>string finalDate = 5;</code>
     * @return The bytes for finalDate.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFinalDateBytes() {
      java.lang.Object ref = finalDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        finalDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENDSUBSCRIPTIONDATE_FIELD_NUMBER = 6;
    private volatile java.lang.Object endSubscriptionDate_;
    /**
     * <code>string endSubscriptionDate = 6;</code>
     * @return The endSubscriptionDate.
     */
    @java.lang.Override
    public java.lang.String getEndSubscriptionDate() {
      java.lang.Object ref = endSubscriptionDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        endSubscriptionDate_ = s;
        return s;
      }
    }
    /**
     * <code>string endSubscriptionDate = 6;</code>
     * @return The bytes for endSubscriptionDate.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEndSubscriptionDateBytes() {
      java.lang.Object ref = endSubscriptionDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        endSubscriptionDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FEETYPE_FIELD_NUMBER = 7;
    private int feeType_;
    /**
     * <code>.example.Subscription.FeeType feeType = 7;</code>
     * @return The enum numeric value on the wire for feeType.
     */
    @java.lang.Override public int getFeeTypeValue() {
      return feeType_;
    }
    /**
     * <code>.example.Subscription.FeeType feeType = 7;</code>
     * @return The feeType.
     */
    @java.lang.Override public com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.FeeType getFeeType() {
      @SuppressWarnings("deprecation")
      com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.FeeType result = com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.FeeType.valueOf(feeType_);
      return result == null ? com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.FeeType.UNRECOGNIZED : result;
    }

    public static final int PAYMENTMETHOD_FIELD_NUMBER = 8;
    private int paymentMethod_;
    /**
     * <code>.example.Subscription.PaymentMethod paymentMethod = 8;</code>
     * @return The enum numeric value on the wire for paymentMethod.
     */
    @java.lang.Override public int getPaymentMethodValue() {
      return paymentMethod_;
    }
    /**
     * <code>.example.Subscription.PaymentMethod paymentMethod = 8;</code>
     * @return The paymentMethod.
     */
    @java.lang.Override public com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.PaymentMethod getPaymentMethod() {
      @SuppressWarnings("deprecation")
      com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.PaymentMethod result = com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.PaymentMethod.valueOf(paymentMethod_);
      return result == null ? com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.PaymentMethod.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(subscriberID_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, subscriberID_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(plan_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, plan_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(initialDate_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, initialDate_);
      }
      if (isActive_ != false) {
        output.writeBool(4, isActive_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(finalDate_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, finalDate_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(endSubscriptionDate_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, endSubscriptionDate_);
      }
      if (feeType_ != com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.FeeType.FEE_TYPE_NA.getNumber()) {
        output.writeEnum(7, feeType_);
      }
      if (paymentMethod_ != com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.PaymentMethod.PAYMENT_METHOD_NA.getNumber()) {
        output.writeEnum(8, paymentMethod_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(subscriberID_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, subscriberID_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(plan_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, plan_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(initialDate_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, initialDate_);
      }
      if (isActive_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, isActive_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(finalDate_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, finalDate_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(endSubscriptionDate_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, endSubscriptionDate_);
      }
      if (feeType_ != com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.FeeType.FEE_TYPE_NA.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, feeType_);
      }
      if (paymentMethod_ != com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.PaymentMethod.PAYMENT_METHOD_NA.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, paymentMethod_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription)) {
        return super.equals(obj);
      }
      com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription other = (com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription) obj;

      if (!getSubscriberID()
          .equals(other.getSubscriberID())) return false;
      if (!getPlan()
          .equals(other.getPlan())) return false;
      if (!getInitialDate()
          .equals(other.getInitialDate())) return false;
      if (getIsActive()
          != other.getIsActive()) return false;
      if (!getFinalDate()
          .equals(other.getFinalDate())) return false;
      if (!getEndSubscriptionDate()
          .equals(other.getEndSubscriptionDate())) return false;
      if (feeType_ != other.feeType_) return false;
      if (paymentMethod_ != other.paymentMethod_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUBSCRIBERID_FIELD_NUMBER;
      hash = (53 * hash) + getSubscriberID().hashCode();
      hash = (37 * hash) + PLAN_FIELD_NUMBER;
      hash = (53 * hash) + getPlan().hashCode();
      hash = (37 * hash) + INITIALDATE_FIELD_NUMBER;
      hash = (53 * hash) + getInitialDate().hashCode();
      hash = (37 * hash) + ISACTIVE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsActive());
      hash = (37 * hash) + FINALDATE_FIELD_NUMBER;
      hash = (53 * hash) + getFinalDate().hashCode();
      hash = (37 * hash) + ENDSUBSCRIPTIONDATE_FIELD_NUMBER;
      hash = (53 * hash) + getEndSubscriptionDate().hashCode();
      hash = (37 * hash) + FEETYPE_FIELD_NUMBER;
      hash = (53 * hash) + feeType_;
      hash = (37 * hash) + PAYMENTMETHOD_FIELD_NUMBER;
      hash = (53 * hash) + paymentMethod_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code example.Subscription}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:example.Subscription)
        com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.internal_static_example_Subscription_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.internal_static_example_Subscription_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.class, com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.Builder.class);
      }

      // Construct using com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        subscriberID_ = "";

        plan_ = "";

        initialDate_ = "";

        isActive_ = false;

        finalDate_ = "";

        endSubscriptionDate_ = "";

        feeType_ = 0;

        paymentMethod_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.internal_static_example_Subscription_descriptor;
      }

      @java.lang.Override
      public com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription getDefaultInstanceForType() {
        return com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription build() {
        com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription buildPartial() {
        com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription result = new com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription(this);
        result.subscriberID_ = subscriberID_;
        result.plan_ = plan_;
        result.initialDate_ = initialDate_;
        result.isActive_ = isActive_;
        result.finalDate_ = finalDate_;
        result.endSubscriptionDate_ = endSubscriptionDate_;
        result.feeType_ = feeType_;
        result.paymentMethod_ = paymentMethod_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription) {
          return mergeFrom((com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription other) {
        if (other == com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.getDefaultInstance()) return this;
        if (!other.getSubscriberID().isEmpty()) {
          subscriberID_ = other.subscriberID_;
          onChanged();
        }
        if (!other.getPlan().isEmpty()) {
          plan_ = other.plan_;
          onChanged();
        }
        if (!other.getInitialDate().isEmpty()) {
          initialDate_ = other.initialDate_;
          onChanged();
        }
        if (other.getIsActive() != false) {
          setIsActive(other.getIsActive());
        }
        if (!other.getFinalDate().isEmpty()) {
          finalDate_ = other.finalDate_;
          onChanged();
        }
        if (!other.getEndSubscriptionDate().isEmpty()) {
          endSubscriptionDate_ = other.endSubscriptionDate_;
          onChanged();
        }
        if (other.feeType_ != 0) {
          setFeeTypeValue(other.getFeeTypeValue());
        }
        if (other.paymentMethod_ != 0) {
          setPaymentMethodValue(other.getPaymentMethodValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                subscriberID_ = input.readStringRequireUtf8();

                break;
              } // case 10
              case 18: {
                plan_ = input.readStringRequireUtf8();

                break;
              } // case 18
              case 26: {
                initialDate_ = input.readStringRequireUtf8();

                break;
              } // case 26
              case 32: {
                isActive_ = input.readBool();

                break;
              } // case 32
              case 42: {
                finalDate_ = input.readStringRequireUtf8();

                break;
              } // case 42
              case 50: {
                endSubscriptionDate_ = input.readStringRequireUtf8();

                break;
              } // case 50
              case 56: {
                feeType_ = input.readEnum();

                break;
              } // case 56
              case 64: {
                paymentMethod_ = input.readEnum();

                break;
              } // case 64
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private java.lang.Object subscriberID_ = "";
      /**
       * <code>string subscriberID = 1;</code>
       * @return The subscriberID.
       */
      public java.lang.String getSubscriberID() {
        java.lang.Object ref = subscriberID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          subscriberID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string subscriberID = 1;</code>
       * @return The bytes for subscriberID.
       */
      public com.google.protobuf.ByteString
          getSubscriberIDBytes() {
        java.lang.Object ref = subscriberID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          subscriberID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string subscriberID = 1;</code>
       * @param value The subscriberID to set.
       * @return This builder for chaining.
       */
      public Builder setSubscriberID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        subscriberID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string subscriberID = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSubscriberID() {
        
        subscriberID_ = getDefaultInstance().getSubscriberID();
        onChanged();
        return this;
      }
      /**
       * <code>string subscriberID = 1;</code>
       * @param value The bytes for subscriberID to set.
       * @return This builder for chaining.
       */
      public Builder setSubscriberIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        subscriberID_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object plan_ = "";
      /**
       * <code>string plan = 2;</code>
       * @return The plan.
       */
      public java.lang.String getPlan() {
        java.lang.Object ref = plan_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          plan_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string plan = 2;</code>
       * @return The bytes for plan.
       */
      public com.google.protobuf.ByteString
          getPlanBytes() {
        java.lang.Object ref = plan_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          plan_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string plan = 2;</code>
       * @param value The plan to set.
       * @return This builder for chaining.
       */
      public Builder setPlan(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        plan_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string plan = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlan() {
        
        plan_ = getDefaultInstance().getPlan();
        onChanged();
        return this;
      }
      /**
       * <code>string plan = 2;</code>
       * @param value The bytes for plan to set.
       * @return This builder for chaining.
       */
      public Builder setPlanBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        plan_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object initialDate_ = "";
      /**
       * <code>string initialDate = 3;</code>
       * @return The initialDate.
       */
      public java.lang.String getInitialDate() {
        java.lang.Object ref = initialDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          initialDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string initialDate = 3;</code>
       * @return The bytes for initialDate.
       */
      public com.google.protobuf.ByteString
          getInitialDateBytes() {
        java.lang.Object ref = initialDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          initialDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string initialDate = 3;</code>
       * @param value The initialDate to set.
       * @return This builder for chaining.
       */
      public Builder setInitialDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        initialDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string initialDate = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearInitialDate() {
        
        initialDate_ = getDefaultInstance().getInitialDate();
        onChanged();
        return this;
      }
      /**
       * <code>string initialDate = 3;</code>
       * @param value The bytes for initialDate to set.
       * @return This builder for chaining.
       */
      public Builder setInitialDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        initialDate_ = value;
        onChanged();
        return this;
      }

      private boolean isActive_ ;
      /**
       * <code>bool isActive = 4;</code>
       * @return The isActive.
       */
      @java.lang.Override
      public boolean getIsActive() {
        return isActive_;
      }
      /**
       * <code>bool isActive = 4;</code>
       * @param value The isActive to set.
       * @return This builder for chaining.
       */
      public Builder setIsActive(boolean value) {
        
        isActive_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isActive = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsActive() {
        
        isActive_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object finalDate_ = "";
      /**
       * <code>string finalDate = 5;</code>
       * @return The finalDate.
       */
      public java.lang.String getFinalDate() {
        java.lang.Object ref = finalDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          finalDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string finalDate = 5;</code>
       * @return The bytes for finalDate.
       */
      public com.google.protobuf.ByteString
          getFinalDateBytes() {
        java.lang.Object ref = finalDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          finalDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string finalDate = 5;</code>
       * @param value The finalDate to set.
       * @return This builder for chaining.
       */
      public Builder setFinalDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        finalDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string finalDate = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearFinalDate() {
        
        finalDate_ = getDefaultInstance().getFinalDate();
        onChanged();
        return this;
      }
      /**
       * <code>string finalDate = 5;</code>
       * @param value The bytes for finalDate to set.
       * @return This builder for chaining.
       */
      public Builder setFinalDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        finalDate_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object endSubscriptionDate_ = "";
      /**
       * <code>string endSubscriptionDate = 6;</code>
       * @return The endSubscriptionDate.
       */
      public java.lang.String getEndSubscriptionDate() {
        java.lang.Object ref = endSubscriptionDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          endSubscriptionDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string endSubscriptionDate = 6;</code>
       * @return The bytes for endSubscriptionDate.
       */
      public com.google.protobuf.ByteString
          getEndSubscriptionDateBytes() {
        java.lang.Object ref = endSubscriptionDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          endSubscriptionDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string endSubscriptionDate = 6;</code>
       * @param value The endSubscriptionDate to set.
       * @return This builder for chaining.
       */
      public Builder setEndSubscriptionDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        endSubscriptionDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string endSubscriptionDate = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearEndSubscriptionDate() {
        
        endSubscriptionDate_ = getDefaultInstance().getEndSubscriptionDate();
        onChanged();
        return this;
      }
      /**
       * <code>string endSubscriptionDate = 6;</code>
       * @param value The bytes for endSubscriptionDate to set.
       * @return This builder for chaining.
       */
      public Builder setEndSubscriptionDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        endSubscriptionDate_ = value;
        onChanged();
        return this;
      }

      private int feeType_ = 0;
      /**
       * <code>.example.Subscription.FeeType feeType = 7;</code>
       * @return The enum numeric value on the wire for feeType.
       */
      @java.lang.Override public int getFeeTypeValue() {
        return feeType_;
      }
      /**
       * <code>.example.Subscription.FeeType feeType = 7;</code>
       * @param value The enum numeric value on the wire for feeType to set.
       * @return This builder for chaining.
       */
      public Builder setFeeTypeValue(int value) {
        
        feeType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.example.Subscription.FeeType feeType = 7;</code>
       * @return The feeType.
       */
      @java.lang.Override
      public com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.FeeType getFeeType() {
        @SuppressWarnings("deprecation")
        com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.FeeType result = com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.FeeType.valueOf(feeType_);
        return result == null ? com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.FeeType.UNRECOGNIZED : result;
      }
      /**
       * <code>.example.Subscription.FeeType feeType = 7;</code>
       * @param value The feeType to set.
       * @return This builder for chaining.
       */
      public Builder setFeeType(com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.FeeType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        feeType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.example.Subscription.FeeType feeType = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearFeeType() {
        
        feeType_ = 0;
        onChanged();
        return this;
      }

      private int paymentMethod_ = 0;
      /**
       * <code>.example.Subscription.PaymentMethod paymentMethod = 8;</code>
       * @return The enum numeric value on the wire for paymentMethod.
       */
      @java.lang.Override public int getPaymentMethodValue() {
        return paymentMethod_;
      }
      /**
       * <code>.example.Subscription.PaymentMethod paymentMethod = 8;</code>
       * @param value The enum numeric value on the wire for paymentMethod to set.
       * @return This builder for chaining.
       */
      public Builder setPaymentMethodValue(int value) {
        
        paymentMethod_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.example.Subscription.PaymentMethod paymentMethod = 8;</code>
       * @return The paymentMethod.
       */
      @java.lang.Override
      public com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.PaymentMethod getPaymentMethod() {
        @SuppressWarnings("deprecation")
        com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.PaymentMethod result = com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.PaymentMethod.valueOf(paymentMethod_);
        return result == null ? com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.PaymentMethod.UNRECOGNIZED : result;
      }
      /**
       * <code>.example.Subscription.PaymentMethod paymentMethod = 8;</code>
       * @param value The paymentMethod to set.
       * @return This builder for chaining.
       */
      public Builder setPaymentMethod(com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.PaymentMethod value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        paymentMethod_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.example.Subscription.PaymentMethod paymentMethod = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearPaymentMethod() {
        
        paymentMethod_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:example.Subscription)
    }

    // @@protoc_insertion_point(class_scope:example.Subscription)
    private static final com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription();
    }

    public static com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Subscription>
        PARSER = new com.google.protobuf.AbstractParser<Subscription>() {
      @java.lang.Override
      public Subscription parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Subscription> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Subscription> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SubscriptionListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:example.SubscriptionList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .example.Subscription subscriptions = 1;</code>
     */
    java.util.List<com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription> 
        getSubscriptionsList();
    /**
     * <code>repeated .example.Subscription subscriptions = 1;</code>
     */
    com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription getSubscriptions(int index);
    /**
     * <code>repeated .example.Subscription subscriptions = 1;</code>
     */
    int getSubscriptionsCount();
    /**
     * <code>repeated .example.Subscription subscriptions = 1;</code>
     */
    java.util.List<? extends com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionOrBuilder> 
        getSubscriptionsOrBuilderList();
    /**
     * <code>repeated .example.Subscription subscriptions = 1;</code>
     */
    com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionOrBuilder getSubscriptionsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code example.SubscriptionList}
   */
  public static final class SubscriptionList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:example.SubscriptionList)
      SubscriptionListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SubscriptionList.newBuilder() to construct.
    private SubscriptionList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SubscriptionList() {
      subscriptions_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SubscriptionList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.internal_static_example_SubscriptionList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.internal_static_example_SubscriptionList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionList.class, com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionList.Builder.class);
    }

    public static final int SUBSCRIPTIONS_FIELD_NUMBER = 1;
    private java.util.List<com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription> subscriptions_;
    /**
     * <code>repeated .example.Subscription subscriptions = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription> getSubscriptionsList() {
      return subscriptions_;
    }
    /**
     * <code>repeated .example.Subscription subscriptions = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionOrBuilder> 
        getSubscriptionsOrBuilderList() {
      return subscriptions_;
    }
    /**
     * <code>repeated .example.Subscription subscriptions = 1;</code>
     */
    @java.lang.Override
    public int getSubscriptionsCount() {
      return subscriptions_.size();
    }
    /**
     * <code>repeated .example.Subscription subscriptions = 1;</code>
     */
    @java.lang.Override
    public com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription getSubscriptions(int index) {
      return subscriptions_.get(index);
    }
    /**
     * <code>repeated .example.Subscription subscriptions = 1;</code>
     */
    @java.lang.Override
    public com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionOrBuilder getSubscriptionsOrBuilder(
        int index) {
      return subscriptions_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < subscriptions_.size(); i++) {
        output.writeMessage(1, subscriptions_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < subscriptions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, subscriptions_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionList)) {
        return super.equals(obj);
      }
      com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionList other = (com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionList) obj;

      if (!getSubscriptionsList()
          .equals(other.getSubscriptionsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getSubscriptionsCount() > 0) {
        hash = (37 * hash) + SUBSCRIPTIONS_FIELD_NUMBER;
        hash = (53 * hash) + getSubscriptionsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code example.SubscriptionList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:example.SubscriptionList)
        com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.internal_static_example_SubscriptionList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.internal_static_example_SubscriptionList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionList.class, com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionList.Builder.class);
      }

      // Construct using com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionList.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (subscriptionsBuilder_ == null) {
          subscriptions_ = java.util.Collections.emptyList();
        } else {
          subscriptions_ = null;
          subscriptionsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.internal_static_example_SubscriptionList_descriptor;
      }

      @java.lang.Override
      public com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionList getDefaultInstanceForType() {
        return com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionList.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionList build() {
        com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionList buildPartial() {
        com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionList result = new com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionList(this);
        int from_bitField0_ = bitField0_;
        if (subscriptionsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            subscriptions_ = java.util.Collections.unmodifiableList(subscriptions_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.subscriptions_ = subscriptions_;
        } else {
          result.subscriptions_ = subscriptionsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionList) {
          return mergeFrom((com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionList other) {
        if (other == com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionList.getDefaultInstance()) return this;
        if (subscriptionsBuilder_ == null) {
          if (!other.subscriptions_.isEmpty()) {
            if (subscriptions_.isEmpty()) {
              subscriptions_ = other.subscriptions_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSubscriptionsIsMutable();
              subscriptions_.addAll(other.subscriptions_);
            }
            onChanged();
          }
        } else {
          if (!other.subscriptions_.isEmpty()) {
            if (subscriptionsBuilder_.isEmpty()) {
              subscriptionsBuilder_.dispose();
              subscriptionsBuilder_ = null;
              subscriptions_ = other.subscriptions_;
              bitField0_ = (bitField0_ & ~0x00000001);
              subscriptionsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSubscriptionsFieldBuilder() : null;
            } else {
              subscriptionsBuilder_.addAllMessages(other.subscriptions_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription m =
                    input.readMessage(
                        com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.parser(),
                        extensionRegistry);
                if (subscriptionsBuilder_ == null) {
                  ensureSubscriptionsIsMutable();
                  subscriptions_.add(m);
                } else {
                  subscriptionsBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription> subscriptions_ =
        java.util.Collections.emptyList();
      private void ensureSubscriptionsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          subscriptions_ = new java.util.ArrayList<com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription>(subscriptions_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription, com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.Builder, com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionOrBuilder> subscriptionsBuilder_;

      /**
       * <code>repeated .example.Subscription subscriptions = 1;</code>
       */
      public java.util.List<com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription> getSubscriptionsList() {
        if (subscriptionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(subscriptions_);
        } else {
          return subscriptionsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .example.Subscription subscriptions = 1;</code>
       */
      public int getSubscriptionsCount() {
        if (subscriptionsBuilder_ == null) {
          return subscriptions_.size();
        } else {
          return subscriptionsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .example.Subscription subscriptions = 1;</code>
       */
      public com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription getSubscriptions(int index) {
        if (subscriptionsBuilder_ == null) {
          return subscriptions_.get(index);
        } else {
          return subscriptionsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .example.Subscription subscriptions = 1;</code>
       */
      public Builder setSubscriptions(
          int index, com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription value) {
        if (subscriptionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubscriptionsIsMutable();
          subscriptions_.set(index, value);
          onChanged();
        } else {
          subscriptionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .example.Subscription subscriptions = 1;</code>
       */
      public Builder setSubscriptions(
          int index, com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.Builder builderForValue) {
        if (subscriptionsBuilder_ == null) {
          ensureSubscriptionsIsMutable();
          subscriptions_.set(index, builderForValue.build());
          onChanged();
        } else {
          subscriptionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .example.Subscription subscriptions = 1;</code>
       */
      public Builder addSubscriptions(com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription value) {
        if (subscriptionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubscriptionsIsMutable();
          subscriptions_.add(value);
          onChanged();
        } else {
          subscriptionsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .example.Subscription subscriptions = 1;</code>
       */
      public Builder addSubscriptions(
          int index, com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription value) {
        if (subscriptionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubscriptionsIsMutable();
          subscriptions_.add(index, value);
          onChanged();
        } else {
          subscriptionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .example.Subscription subscriptions = 1;</code>
       */
      public Builder addSubscriptions(
          com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.Builder builderForValue) {
        if (subscriptionsBuilder_ == null) {
          ensureSubscriptionsIsMutable();
          subscriptions_.add(builderForValue.build());
          onChanged();
        } else {
          subscriptionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .example.Subscription subscriptions = 1;</code>
       */
      public Builder addSubscriptions(
          int index, com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.Builder builderForValue) {
        if (subscriptionsBuilder_ == null) {
          ensureSubscriptionsIsMutable();
          subscriptions_.add(index, builderForValue.build());
          onChanged();
        } else {
          subscriptionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .example.Subscription subscriptions = 1;</code>
       */
      public Builder addAllSubscriptions(
          java.lang.Iterable<? extends com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription> values) {
        if (subscriptionsBuilder_ == null) {
          ensureSubscriptionsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, subscriptions_);
          onChanged();
        } else {
          subscriptionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .example.Subscription subscriptions = 1;</code>
       */
      public Builder clearSubscriptions() {
        if (subscriptionsBuilder_ == null) {
          subscriptions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          subscriptionsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .example.Subscription subscriptions = 1;</code>
       */
      public Builder removeSubscriptions(int index) {
        if (subscriptionsBuilder_ == null) {
          ensureSubscriptionsIsMutable();
          subscriptions_.remove(index);
          onChanged();
        } else {
          subscriptionsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .example.Subscription subscriptions = 1;</code>
       */
      public com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.Builder getSubscriptionsBuilder(
          int index) {
        return getSubscriptionsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .example.Subscription subscriptions = 1;</code>
       */
      public com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionOrBuilder getSubscriptionsOrBuilder(
          int index) {
        if (subscriptionsBuilder_ == null) {
          return subscriptions_.get(index);  } else {
          return subscriptionsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .example.Subscription subscriptions = 1;</code>
       */
      public java.util.List<? extends com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionOrBuilder> 
           getSubscriptionsOrBuilderList() {
        if (subscriptionsBuilder_ != null) {
          return subscriptionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(subscriptions_);
        }
      }
      /**
       * <code>repeated .example.Subscription subscriptions = 1;</code>
       */
      public com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.Builder addSubscriptionsBuilder() {
        return getSubscriptionsFieldBuilder().addBuilder(
            com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.getDefaultInstance());
      }
      /**
       * <code>repeated .example.Subscription subscriptions = 1;</code>
       */
      public com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.Builder addSubscriptionsBuilder(
          int index) {
        return getSubscriptionsFieldBuilder().addBuilder(
            index, com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.getDefaultInstance());
      }
      /**
       * <code>repeated .example.Subscription subscriptions = 1;</code>
       */
      public java.util.List<com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.Builder> 
           getSubscriptionsBuilderList() {
        return getSubscriptionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription, com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.Builder, com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionOrBuilder> 
          getSubscriptionsFieldBuilder() {
        if (subscriptionsBuilder_ == null) {
          subscriptionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription, com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.Subscription.Builder, com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionOrBuilder>(
                  subscriptions_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          subscriptions_ = null;
        }
        return subscriptionsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:example.SubscriptionList)
    }

    // @@protoc_insertion_point(class_scope:example.SubscriptionList)
    private static final com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionList();
    }

    public static com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SubscriptionList>
        PARSER = new com.google.protobuf.AbstractParser<SubscriptionList>() {
      @java.lang.Override
      public SubscriptionList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SubscriptionList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SubscriptionList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.sisdi_subscriptions.subscriptionmanagement.model.proto.SubscriptionEntity.SubscriptionList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_Subscription_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_example_Subscription_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_SubscriptionList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_example_SubscriptionList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030SubscriptionEntity.proto\022\007example\"\347\002\n\014" +
      "Subscription\022\024\n\014subscriberID\030\001 \001(\t\022\014\n\004pl" +
      "an\030\002 \001(\t\022\023\n\013initialDate\030\003 \001(\t\022\020\n\010isActiv" +
      "e\030\004 \001(\010\022\021\n\tfinalDate\030\005 \001(\t\022\033\n\023endSubscri" +
      "ptionDate\030\006 \001(\t\022.\n\007feeType\030\007 \001(\0162\035.examp" +
      "le.Subscription.FeeType\022:\n\rpaymentMethod" +
      "\030\010 \001(\0162#.example.Subscription.PaymentMet" +
      "hod\"3\n\007FeeType\022\017\n\013FEE_TYPE_NA\020\000\022\013\n\007MONTH" +
      "LY\020\001\022\n\n\006ANNUAL\020\002\";\n\rPaymentMethod\022\025\n\021PAY" +
      "MENT_METHOD_NA\020\000\022\t\n\005MBWAY\020\001\022\010\n\004CARD\020\002\"@\n" +
      "\020SubscriptionList\022,\n\rsubscriptions\030\001 \003(\013" +
      "2\025.example.SubscriptionBD\nBcom.example.s" +
      "isdi_subscriptions.subscriptionmanagemen" +
      "t.model.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_example_Subscription_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_example_Subscription_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_example_Subscription_descriptor,
        new java.lang.String[] { "SubscriberID", "Plan", "InitialDate", "IsActive", "FinalDate", "EndSubscriptionDate", "FeeType", "PaymentMethod", });
    internal_static_example_SubscriptionList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_example_SubscriptionList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_example_SubscriptionList_descriptor,
        new java.lang.String[] { "Subscriptions", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
