// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PlanRequests.proto

package com.example.sisdi_plans.planmanagement.api.proto;

public final class PlanRequests {
  private PlanRequests() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EditPlanRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:example.EditPlanRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string description = 1;</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 1;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>string numberOfMinutes = 2;</code>
     * @return The numberOfMinutes.
     */
    java.lang.String getNumberOfMinutes();
    /**
     * <code>string numberOfMinutes = 2;</code>
     * @return The bytes for numberOfMinutes.
     */
    com.google.protobuf.ByteString
        getNumberOfMinutesBytes();

    /**
     * <code>string musicSuggestions = 3;</code>
     * @return The musicSuggestions.
     */
    java.lang.String getMusicSuggestions();
    /**
     * <code>string musicSuggestions = 3;</code>
     * @return The bytes for musicSuggestions.
     */
    com.google.protobuf.ByteString
        getMusicSuggestionsBytes();

    /**
     * <code>string musicCollections = 4;</code>
     * @return The musicCollections.
     */
    java.lang.String getMusicCollections();
    /**
     * <code>string musicCollections = 4;</code>
     * @return The bytes for musicCollections.
     */
    com.google.protobuf.ByteString
        getMusicCollectionsBytes();
  }
  /**
   * Protobuf type {@code example.EditPlanRequest}
   */
  public static final class EditPlanRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:example.EditPlanRequest)
      EditPlanRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EditPlanRequest.newBuilder() to construct.
    private EditPlanRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EditPlanRequest() {
      description_ = "";
      numberOfMinutes_ = "";
      musicSuggestions_ = "";
      musicCollections_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EditPlanRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.internal_static_example_EditPlanRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.internal_static_example_EditPlanRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.EditPlanRequest.class, com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.EditPlanRequest.Builder.class);
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 1;
    private volatile java.lang.Object description_;
    /**
     * <code>string description = 1;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 1;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NUMBEROFMINUTES_FIELD_NUMBER = 2;
    private volatile java.lang.Object numberOfMinutes_;
    /**
     * <code>string numberOfMinutes = 2;</code>
     * @return The numberOfMinutes.
     */
    @java.lang.Override
    public java.lang.String getNumberOfMinutes() {
      java.lang.Object ref = numberOfMinutes_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        numberOfMinutes_ = s;
        return s;
      }
    }
    /**
     * <code>string numberOfMinutes = 2;</code>
     * @return The bytes for numberOfMinutes.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNumberOfMinutesBytes() {
      java.lang.Object ref = numberOfMinutes_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        numberOfMinutes_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MUSICSUGGESTIONS_FIELD_NUMBER = 3;
    private volatile java.lang.Object musicSuggestions_;
    /**
     * <code>string musicSuggestions = 3;</code>
     * @return The musicSuggestions.
     */
    @java.lang.Override
    public java.lang.String getMusicSuggestions() {
      java.lang.Object ref = musicSuggestions_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        musicSuggestions_ = s;
        return s;
      }
    }
    /**
     * <code>string musicSuggestions = 3;</code>
     * @return The bytes for musicSuggestions.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMusicSuggestionsBytes() {
      java.lang.Object ref = musicSuggestions_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        musicSuggestions_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MUSICCOLLECTIONS_FIELD_NUMBER = 4;
    private volatile java.lang.Object musicCollections_;
    /**
     * <code>string musicCollections = 4;</code>
     * @return The musicCollections.
     */
    @java.lang.Override
    public java.lang.String getMusicCollections() {
      java.lang.Object ref = musicCollections_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        musicCollections_ = s;
        return s;
      }
    }
    /**
     * <code>string musicCollections = 4;</code>
     * @return The bytes for musicCollections.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMusicCollectionsBytes() {
      java.lang.Object ref = musicCollections_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        musicCollections_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, description_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(numberOfMinutes_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, numberOfMinutes_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(musicSuggestions_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, musicSuggestions_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(musicCollections_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, musicCollections_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, description_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(numberOfMinutes_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, numberOfMinutes_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(musicSuggestions_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, musicSuggestions_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(musicCollections_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, musicCollections_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.EditPlanRequest)) {
        return super.equals(obj);
      }
      com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.EditPlanRequest other = (com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.EditPlanRequest) obj;

      if (!getDescription()
          .equals(other.getDescription())) return false;
      if (!getNumberOfMinutes()
          .equals(other.getNumberOfMinutes())) return false;
      if (!getMusicSuggestions()
          .equals(other.getMusicSuggestions())) return false;
      if (!getMusicCollections()
          .equals(other.getMusicCollections())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (37 * hash) + NUMBEROFMINUTES_FIELD_NUMBER;
      hash = (53 * hash) + getNumberOfMinutes().hashCode();
      hash = (37 * hash) + MUSICSUGGESTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getMusicSuggestions().hashCode();
      hash = (37 * hash) + MUSICCOLLECTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getMusicCollections().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.EditPlanRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.EditPlanRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.EditPlanRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.EditPlanRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.EditPlanRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.EditPlanRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.EditPlanRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.EditPlanRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.EditPlanRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.EditPlanRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.EditPlanRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.EditPlanRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.EditPlanRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code example.EditPlanRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:example.EditPlanRequest)
        com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.EditPlanRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.internal_static_example_EditPlanRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.internal_static_example_EditPlanRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.EditPlanRequest.class, com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.EditPlanRequest.Builder.class);
      }

      // Construct using com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.EditPlanRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        description_ = "";

        numberOfMinutes_ = "";

        musicSuggestions_ = "";

        musicCollections_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.internal_static_example_EditPlanRequest_descriptor;
      }

      @java.lang.Override
      public com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.EditPlanRequest getDefaultInstanceForType() {
        return com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.EditPlanRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.EditPlanRequest build() {
        com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.EditPlanRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.EditPlanRequest buildPartial() {
        com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.EditPlanRequest result = new com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.EditPlanRequest(this);
        result.description_ = description_;
        result.numberOfMinutes_ = numberOfMinutes_;
        result.musicSuggestions_ = musicSuggestions_;
        result.musicCollections_ = musicCollections_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.EditPlanRequest) {
          return mergeFrom((com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.EditPlanRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.EditPlanRequest other) {
        if (other == com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.EditPlanRequest.getDefaultInstance()) return this;
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        if (!other.getNumberOfMinutes().isEmpty()) {
          numberOfMinutes_ = other.numberOfMinutes_;
          onChanged();
        }
        if (!other.getMusicSuggestions().isEmpty()) {
          musicSuggestions_ = other.musicSuggestions_;
          onChanged();
        }
        if (!other.getMusicCollections().isEmpty()) {
          musicCollections_ = other.musicCollections_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                description_ = input.readStringRequireUtf8();

                break;
              } // case 10
              case 18: {
                numberOfMinutes_ = input.readStringRequireUtf8();

                break;
              } // case 18
              case 26: {
                musicSuggestions_ = input.readStringRequireUtf8();

                break;
              } // case 26
              case 34: {
                musicCollections_ = input.readStringRequireUtf8();

                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 1;</code>
       * @return The description.
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 1;</code>
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 1;</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string description = 1;</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object numberOfMinutes_ = "";
      /**
       * <code>string numberOfMinutes = 2;</code>
       * @return The numberOfMinutes.
       */
      public java.lang.String getNumberOfMinutes() {
        java.lang.Object ref = numberOfMinutes_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          numberOfMinutes_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string numberOfMinutes = 2;</code>
       * @return The bytes for numberOfMinutes.
       */
      public com.google.protobuf.ByteString
          getNumberOfMinutesBytes() {
        java.lang.Object ref = numberOfMinutes_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          numberOfMinutes_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string numberOfMinutes = 2;</code>
       * @param value The numberOfMinutes to set.
       * @return This builder for chaining.
       */
      public Builder setNumberOfMinutes(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        numberOfMinutes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string numberOfMinutes = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumberOfMinutes() {
        
        numberOfMinutes_ = getDefaultInstance().getNumberOfMinutes();
        onChanged();
        return this;
      }
      /**
       * <code>string numberOfMinutes = 2;</code>
       * @param value The bytes for numberOfMinutes to set.
       * @return This builder for chaining.
       */
      public Builder setNumberOfMinutesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        numberOfMinutes_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object musicSuggestions_ = "";
      /**
       * <code>string musicSuggestions = 3;</code>
       * @return The musicSuggestions.
       */
      public java.lang.String getMusicSuggestions() {
        java.lang.Object ref = musicSuggestions_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          musicSuggestions_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string musicSuggestions = 3;</code>
       * @return The bytes for musicSuggestions.
       */
      public com.google.protobuf.ByteString
          getMusicSuggestionsBytes() {
        java.lang.Object ref = musicSuggestions_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          musicSuggestions_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string musicSuggestions = 3;</code>
       * @param value The musicSuggestions to set.
       * @return This builder for chaining.
       */
      public Builder setMusicSuggestions(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        musicSuggestions_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string musicSuggestions = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMusicSuggestions() {
        
        musicSuggestions_ = getDefaultInstance().getMusicSuggestions();
        onChanged();
        return this;
      }
      /**
       * <code>string musicSuggestions = 3;</code>
       * @param value The bytes for musicSuggestions to set.
       * @return This builder for chaining.
       */
      public Builder setMusicSuggestionsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        musicSuggestions_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object musicCollections_ = "";
      /**
       * <code>string musicCollections = 4;</code>
       * @return The musicCollections.
       */
      public java.lang.String getMusicCollections() {
        java.lang.Object ref = musicCollections_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          musicCollections_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string musicCollections = 4;</code>
       * @return The bytes for musicCollections.
       */
      public com.google.protobuf.ByteString
          getMusicCollectionsBytes() {
        java.lang.Object ref = musicCollections_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          musicCollections_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string musicCollections = 4;</code>
       * @param value The musicCollections to set.
       * @return This builder for chaining.
       */
      public Builder setMusicCollections(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        musicCollections_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string musicCollections = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMusicCollections() {
        
        musicCollections_ = getDefaultInstance().getMusicCollections();
        onChanged();
        return this;
      }
      /**
       * <code>string musicCollections = 4;</code>
       * @param value The bytes for musicCollections to set.
       * @return This builder for chaining.
       */
      public Builder setMusicCollectionsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        musicCollections_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:example.EditPlanRequest)
    }

    // @@protoc_insertion_point(class_scope:example.EditPlanRequest)
    private static final com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.EditPlanRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.EditPlanRequest();
    }

    public static com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.EditPlanRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EditPlanRequest>
        PARSER = new com.google.protobuf.AbstractParser<EditPlanRequest>() {
      @java.lang.Override
      public EditPlanRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<EditPlanRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EditPlanRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.EditPlanRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CreatePlanRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:example.CreatePlanRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string description = 2;</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 2;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>int32 numberOfMinutes = 3;</code>
     * @return The numberOfMinutes.
     */
    int getNumberOfMinutes();

    /**
     * <code>string musicSuggestions = 4;</code>
     * @return The musicSuggestions.
     */
    java.lang.String getMusicSuggestions();
    /**
     * <code>string musicSuggestions = 4;</code>
     * @return The bytes for musicSuggestions.
     */
    com.google.protobuf.ByteString
        getMusicSuggestionsBytes();

    /**
     * <code>int32 musicCollections = 5;</code>
     * @return The musicCollections.
     */
    int getMusicCollections();

    /**
     * <code>float monthlyFee = 6;</code>
     * @return The monthlyFee.
     */
    float getMonthlyFee();

    /**
     * <code>float annualFee = 7;</code>
     * @return The annualFee.
     */
    float getAnnualFee();
  }
  /**
   * Protobuf type {@code example.CreatePlanRequest}
   */
  public static final class CreatePlanRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:example.CreatePlanRequest)
      CreatePlanRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CreatePlanRequest.newBuilder() to construct.
    private CreatePlanRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CreatePlanRequest() {
      name_ = "";
      description_ = "";
      musicSuggestions_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CreatePlanRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.internal_static_example_CreatePlanRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.internal_static_example_CreatePlanRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.CreatePlanRequest.class, com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.CreatePlanRequest.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 2;
    private volatile java.lang.Object description_;
    /**
     * <code>string description = 2;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 2;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NUMBEROFMINUTES_FIELD_NUMBER = 3;
    private int numberOfMinutes_;
    /**
     * <code>int32 numberOfMinutes = 3;</code>
     * @return The numberOfMinutes.
     */
    @java.lang.Override
    public int getNumberOfMinutes() {
      return numberOfMinutes_;
    }

    public static final int MUSICSUGGESTIONS_FIELD_NUMBER = 4;
    private volatile java.lang.Object musicSuggestions_;
    /**
     * <code>string musicSuggestions = 4;</code>
     * @return The musicSuggestions.
     */
    @java.lang.Override
    public java.lang.String getMusicSuggestions() {
      java.lang.Object ref = musicSuggestions_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        musicSuggestions_ = s;
        return s;
      }
    }
    /**
     * <code>string musicSuggestions = 4;</code>
     * @return The bytes for musicSuggestions.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMusicSuggestionsBytes() {
      java.lang.Object ref = musicSuggestions_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        musicSuggestions_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MUSICCOLLECTIONS_FIELD_NUMBER = 5;
    private int musicCollections_;
    /**
     * <code>int32 musicCollections = 5;</code>
     * @return The musicCollections.
     */
    @java.lang.Override
    public int getMusicCollections() {
      return musicCollections_;
    }

    public static final int MONTHLYFEE_FIELD_NUMBER = 6;
    private float monthlyFee_;
    /**
     * <code>float monthlyFee = 6;</code>
     * @return The monthlyFee.
     */
    @java.lang.Override
    public float getMonthlyFee() {
      return monthlyFee_;
    }

    public static final int ANNUALFEE_FIELD_NUMBER = 7;
    private float annualFee_;
    /**
     * <code>float annualFee = 7;</code>
     * @return The annualFee.
     */
    @java.lang.Override
    public float getAnnualFee() {
      return annualFee_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, description_);
      }
      if (numberOfMinutes_ != 0) {
        output.writeInt32(3, numberOfMinutes_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(musicSuggestions_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, musicSuggestions_);
      }
      if (musicCollections_ != 0) {
        output.writeInt32(5, musicCollections_);
      }
      if (java.lang.Float.floatToRawIntBits(monthlyFee_) != 0) {
        output.writeFloat(6, monthlyFee_);
      }
      if (java.lang.Float.floatToRawIntBits(annualFee_) != 0) {
        output.writeFloat(7, annualFee_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, description_);
      }
      if (numberOfMinutes_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, numberOfMinutes_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(musicSuggestions_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, musicSuggestions_);
      }
      if (musicCollections_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, musicCollections_);
      }
      if (java.lang.Float.floatToRawIntBits(monthlyFee_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, monthlyFee_);
      }
      if (java.lang.Float.floatToRawIntBits(annualFee_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(7, annualFee_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.CreatePlanRequest)) {
        return super.equals(obj);
      }
      com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.CreatePlanRequest other = (com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.CreatePlanRequest) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getDescription()
          .equals(other.getDescription())) return false;
      if (getNumberOfMinutes()
          != other.getNumberOfMinutes()) return false;
      if (!getMusicSuggestions()
          .equals(other.getMusicSuggestions())) return false;
      if (getMusicCollections()
          != other.getMusicCollections()) return false;
      if (java.lang.Float.floatToIntBits(getMonthlyFee())
          != java.lang.Float.floatToIntBits(
              other.getMonthlyFee())) return false;
      if (java.lang.Float.floatToIntBits(getAnnualFee())
          != java.lang.Float.floatToIntBits(
              other.getAnnualFee())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (37 * hash) + NUMBEROFMINUTES_FIELD_NUMBER;
      hash = (53 * hash) + getNumberOfMinutes();
      hash = (37 * hash) + MUSICSUGGESTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getMusicSuggestions().hashCode();
      hash = (37 * hash) + MUSICCOLLECTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getMusicCollections();
      hash = (37 * hash) + MONTHLYFEE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getMonthlyFee());
      hash = (37 * hash) + ANNUALFEE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getAnnualFee());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.CreatePlanRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.CreatePlanRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.CreatePlanRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.CreatePlanRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.CreatePlanRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.CreatePlanRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.CreatePlanRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.CreatePlanRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.CreatePlanRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.CreatePlanRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.CreatePlanRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.CreatePlanRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.CreatePlanRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code example.CreatePlanRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:example.CreatePlanRequest)
        com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.CreatePlanRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.internal_static_example_CreatePlanRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.internal_static_example_CreatePlanRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.CreatePlanRequest.class, com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.CreatePlanRequest.Builder.class);
      }

      // Construct using com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.CreatePlanRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        description_ = "";

        numberOfMinutes_ = 0;

        musicSuggestions_ = "";

        musicCollections_ = 0;

        monthlyFee_ = 0F;

        annualFee_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.internal_static_example_CreatePlanRequest_descriptor;
      }

      @java.lang.Override
      public com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.CreatePlanRequest getDefaultInstanceForType() {
        return com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.CreatePlanRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.CreatePlanRequest build() {
        com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.CreatePlanRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.CreatePlanRequest buildPartial() {
        com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.CreatePlanRequest result = new com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.CreatePlanRequest(this);
        result.name_ = name_;
        result.description_ = description_;
        result.numberOfMinutes_ = numberOfMinutes_;
        result.musicSuggestions_ = musicSuggestions_;
        result.musicCollections_ = musicCollections_;
        result.monthlyFee_ = monthlyFee_;
        result.annualFee_ = annualFee_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.CreatePlanRequest) {
          return mergeFrom((com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.CreatePlanRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.CreatePlanRequest other) {
        if (other == com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.CreatePlanRequest.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        if (other.getNumberOfMinutes() != 0) {
          setNumberOfMinutes(other.getNumberOfMinutes());
        }
        if (!other.getMusicSuggestions().isEmpty()) {
          musicSuggestions_ = other.musicSuggestions_;
          onChanged();
        }
        if (other.getMusicCollections() != 0) {
          setMusicCollections(other.getMusicCollections());
        }
        if (other.getMonthlyFee() != 0F) {
          setMonthlyFee(other.getMonthlyFee());
        }
        if (other.getAnnualFee() != 0F) {
          setAnnualFee(other.getAnnualFee());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                name_ = input.readStringRequireUtf8();

                break;
              } // case 10
              case 18: {
                description_ = input.readStringRequireUtf8();

                break;
              } // case 18
              case 24: {
                numberOfMinutes_ = input.readInt32();

                break;
              } // case 24
              case 34: {
                musicSuggestions_ = input.readStringRequireUtf8();

                break;
              } // case 34
              case 40: {
                musicCollections_ = input.readInt32();

                break;
              } // case 40
              case 53: {
                monthlyFee_ = input.readFloat();

                break;
              } // case 53
              case 61: {
                annualFee_ = input.readFloat();

                break;
              } // case 61
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 2;</code>
       * @return The description.
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 2;</code>
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 2;</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string description = 2;</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }

      private int numberOfMinutes_ ;
      /**
       * <code>int32 numberOfMinutes = 3;</code>
       * @return The numberOfMinutes.
       */
      @java.lang.Override
      public int getNumberOfMinutes() {
        return numberOfMinutes_;
      }
      /**
       * <code>int32 numberOfMinutes = 3;</code>
       * @param value The numberOfMinutes to set.
       * @return This builder for chaining.
       */
      public Builder setNumberOfMinutes(int value) {
        
        numberOfMinutes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 numberOfMinutes = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumberOfMinutes() {
        
        numberOfMinutes_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object musicSuggestions_ = "";
      /**
       * <code>string musicSuggestions = 4;</code>
       * @return The musicSuggestions.
       */
      public java.lang.String getMusicSuggestions() {
        java.lang.Object ref = musicSuggestions_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          musicSuggestions_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string musicSuggestions = 4;</code>
       * @return The bytes for musicSuggestions.
       */
      public com.google.protobuf.ByteString
          getMusicSuggestionsBytes() {
        java.lang.Object ref = musicSuggestions_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          musicSuggestions_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string musicSuggestions = 4;</code>
       * @param value The musicSuggestions to set.
       * @return This builder for chaining.
       */
      public Builder setMusicSuggestions(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        musicSuggestions_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string musicSuggestions = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMusicSuggestions() {
        
        musicSuggestions_ = getDefaultInstance().getMusicSuggestions();
        onChanged();
        return this;
      }
      /**
       * <code>string musicSuggestions = 4;</code>
       * @param value The bytes for musicSuggestions to set.
       * @return This builder for chaining.
       */
      public Builder setMusicSuggestionsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        musicSuggestions_ = value;
        onChanged();
        return this;
      }

      private int musicCollections_ ;
      /**
       * <code>int32 musicCollections = 5;</code>
       * @return The musicCollections.
       */
      @java.lang.Override
      public int getMusicCollections() {
        return musicCollections_;
      }
      /**
       * <code>int32 musicCollections = 5;</code>
       * @param value The musicCollections to set.
       * @return This builder for chaining.
       */
      public Builder setMusicCollections(int value) {
        
        musicCollections_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 musicCollections = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearMusicCollections() {
        
        musicCollections_ = 0;
        onChanged();
        return this;
      }

      private float monthlyFee_ ;
      /**
       * <code>float monthlyFee = 6;</code>
       * @return The monthlyFee.
       */
      @java.lang.Override
      public float getMonthlyFee() {
        return monthlyFee_;
      }
      /**
       * <code>float monthlyFee = 6;</code>
       * @param value The monthlyFee to set.
       * @return This builder for chaining.
       */
      public Builder setMonthlyFee(float value) {
        
        monthlyFee_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float monthlyFee = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearMonthlyFee() {
        
        monthlyFee_ = 0F;
        onChanged();
        return this;
      }

      private float annualFee_ ;
      /**
       * <code>float annualFee = 7;</code>
       * @return The annualFee.
       */
      @java.lang.Override
      public float getAnnualFee() {
        return annualFee_;
      }
      /**
       * <code>float annualFee = 7;</code>
       * @param value The annualFee to set.
       * @return This builder for chaining.
       */
      public Builder setAnnualFee(float value) {
        
        annualFee_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float annualFee = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearAnnualFee() {
        
        annualFee_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:example.CreatePlanRequest)
    }

    // @@protoc_insertion_point(class_scope:example.CreatePlanRequest)
    private static final com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.CreatePlanRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.CreatePlanRequest();
    }

    public static com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.CreatePlanRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CreatePlanRequest>
        PARSER = new com.google.protobuf.AbstractParser<CreatePlanRequest>() {
      @java.lang.Override
      public CreatePlanRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CreatePlanRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CreatePlanRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.example.sisdi_plans.planmanagement.api.proto.PlanRequests.CreatePlanRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_EditPlanRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_example_EditPlanRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_CreatePlanRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_example_CreatePlanRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022PlanRequests.proto\022\007example\"s\n\017EditPla" +
      "nRequest\022\023\n\013description\030\001 \001(\t\022\027\n\017numberO" +
      "fMinutes\030\002 \001(\t\022\030\n\020musicSuggestions\030\003 \001(\t" +
      "\022\030\n\020musicCollections\030\004 \001(\t\"\252\001\n\021CreatePla" +
      "nRequest\022\014\n\004name\030\001 \001(\t\022\023\n\013description\030\002 " +
      "\001(\t\022\027\n\017numberOfMinutes\030\003 \001(\005\022\030\n\020musicSug" +
      "gestions\030\004 \001(\t\022\030\n\020musicCollections\030\005 \001(\005" +
      "\022\022\n\nmonthlyFee\030\006 \001(\002\022\021\n\tannualFee\030\007 \001(\002B" +
      "2\n0com.example.sisdi_plans.planmanagemen" +
      "t.api.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_example_EditPlanRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_example_EditPlanRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_example_EditPlanRequest_descriptor,
        new java.lang.String[] { "Description", "NumberOfMinutes", "MusicSuggestions", "MusicCollections", });
    internal_static_example_CreatePlanRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_example_CreatePlanRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_example_CreatePlanRequest_descriptor,
        new java.lang.String[] { "Name", "Description", "NumberOfMinutes", "MusicSuggestions", "MusicCollections", "MonthlyFee", "AnnualFee", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
